=== DOCGroup/CoSMIC/CoSMIC/tests/LEESA/xo-impedance/impedance.xsd
<?xml version="1.0"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:xse="http://www.codesynthesis.com/xmlns/xml-schema-extension"
            xmlns:impedance="http://www.dre.vanderbilt.edu/impedance"
            targetNamespace="http://www.dre.vanderbilt.edu/impedance">

  <xsd:complexType name="Regular">
    <!-- Note b and c are in fact (b,c)*. They deserialize fine but
         serealization groups all b together followed by all c. 
         Such XML does not validate while reading back in!  -->
      <xsd:sequence>
        <xsd:element name="a" type="xsd:string"/>
          <xsd:sequence maxOccurs="unbounded">
            <xsd:element name="b" type="xsd:int"/>
            <xsd:element name="c" type="xsd:string"/>
          </xsd:sequence>
      </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="Point" mixed="true">
    <xsd:sequence>
      <xsd:element name="x" type="xsd:integer" />
      <xsd:element name="y" type="xsd:integer" />
      <!-- Note the use of xsd::Anytype below. Default is xsd:anyType. -->
      <xsd:element name="something" minOccurs="0" />
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="MultiplePoints">
      <!-- While serializing, all points get together and all dots get
           together. Such XML can't be read back in. This appears to be
           a special case of the Regular type above. -->
    <xsd:sequence> 
      <xsd:element name="point" type="impedance:Point" 
                   maxOccurs="3" minOccurs="2"/>
      <xsd:element name="dot"   type="impedance:Point" />
      <xsd:element name="point" type="impedance:Point" minOccurs="0"/>
    </xsd:sequence>
  </xsd:complexType>

  
  <xsd:complexType name="Top">
    <xsd:sequence>
      <xsd:element name="regular" type="impedance:Regular" />
      <xsd:element name="points" type="impedance:MultiplePoints" />
      <xsd:element name="foobar">
        <xsd:complexType>
          <!-- An anonymous sequence below. Name-mangling should be used
               to derive an unique name. xsd combines the first two element
               names. The same for anonymous xsd:choice. -->
          <xsd:sequence>
            <xsd:element name="foo" type="xsd:integer"/>
            <xsd:element name="bar" type="xsd:integer"/>
            <xsd:element name="zoo" type="xsd:integer"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>


  <xsd:element name="top" type="impedance:Top" />

</xsd:schema>

=== DOCGroup/CoSMIC/CoSMIC/tests/LEESA/xo-impedance/impedance.xml
<?xml version="1.0"?>

<impedance:top xmlns:impedance="http://www.dre.vanderbilt.edu/impedance"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.dre.vanderbilt.edu/impedance impedance.xsd">
  <regular>
    <a>Nashville</a>
    <!-- Note b and c are in fact (b,c)*. They deserialize fine but
         serealization groups all b together followed by all c. 
         Such XML does not validate while reading back in!  -->
    <b>1</b>
    <c>Memphis</c>
    <b>2</b>
    <c>New York</c>
    <b>3</b>
    <c>San Fancisco</c>
  </regular>

      <!-- While serializing, all points get together and all dots get
           together. Such XML can't be read back in. This appears to be
           a special case of the Regular type above. -->
  <points>
    <point> 
      <x>10</x>
      <y>20</y>
    </point>
    <point>
      <x>50</x>
      <y>60</y>
    </point>
    <!-- Mixed contents don't seem to round-trip. -->
    <dot>This is
      <x>1</x>a 
      <y>2</y>dot
    </dot>
    <point>
      <x>100</x>
      <y>200</y>
      <!-- Anytypes don't seem to round-trip. -->
      <something>Something</something>
    </point>
  </points>

  <foobar>
     <!-- An anonymous sequence below. Name-mangling should be used
          to derive an unique name. xsd combines the first two element
          names. The same for anonymous xsd:choice. -->
    <foo>99</foo>
    <bar>11</bar>
    <zoo>0</zoo>
  </foobar>

</impedance:top>
