=== DOCGroup/CoSMIC/CoSMIC/tests/LEESA/library-xsd/library.xsd
<?xml version="1.0"?>

<!--

file      : examples/cxx/tree/library/library.xsd
author    : Boris Kolpackov <boris@codesynthesis.com>
copyright : not copyrighted - public domain

-->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:xse="http://www.codesynthesis.com/xmlns/xml-schema-extension"
            xmlns:lib="http://www.codesynthesis.com/library"
            targetNamespace="http://www.codesynthesis.com/library">

  <xsd:simpleType name="isbn">
    <xsd:restriction base="xsd:unsignedInt"/>
  </xsd:simpleType>

  <xsd:complexType name="title">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="lang">
        <xsd:simpleType>
          <xsd:restriction base="xsd:language" />
        </xsd:simpleType>
        </xsd:attribute>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:simpleType name="genre">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="romance"/>
      <xsd:enumeration value="fiction"/>
      <xsd:enumeration value="horror"/>
      <xsd:enumeration value="history"/>
      <xsd:enumeration value="philosophy"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="author">
    <xsd:sequence>
      <xsd:element name="name">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string" />
        </xsd:simpleType>
      </xsd:element>
      <xsd:element name="born">
         <xsd:simpleType>
           <xsd:restriction base="xsd:date" />
         </xsd:simpleType>
       </xsd:element>
      <xsd:element name="died" minOccurs="0">
         <xsd:simpleType>
           <xsd:restriction base="xsd:date" />
         </xsd:simpleType>
         </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="book">
    <xsd:sequence>
      <xsd:element name="isbn" type="lib:isbn"/>
      <xsd:element name="title" type="lib:title"/>
      <xsd:element name="genre" type="lib:genre"/>
      <xsd:element name="author" type="lib:author" maxOccurs="unbounded"/>
       <xsd:element name="price" type="xsd:double" maxOccurs="unbounded"/>
         <!--xsd:simpleType>
           <xsd:restriction base="xsd:double" />
         </xsd:simpleType>
       </xsd:element-->
     </xsd:sequence>
    <xsd:attribute name="available" default="true">
      <xsd:simpleType>
        <xsd:restriction base="xsd:boolean" />
      </xsd:simpleType>
    </xsd:attribute>
  </xsd:complexType>

  <xsd:complexType name="catalog">
    <xsd:sequence>
      <xsd:element name="book" type="lib:book" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:element name="catalog" type="lib:catalog"/>

</xsd:schema>

=== DOCGroup/CoSMIC/CoSMIC/tests/LEESA/library-xsd/library.xml
<?xml version="1.0"?>

<!--

file      : examples/cxx/tree/library/library.xml
author    : Boris Kolpackov <boris@codesynthesis.com>
copyright : not copyrighted - public domain

-->

<lib:catalog xmlns:lib="http://www.codesynthesis.com/library"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	     xsi:schemaLocation="http://www.codesynthesis.com/library library.xsd">

  <book available="false">
    <isbn>0679760806</isbn>
    <title>The Master and Margarita</title>
    <genre>fiction</genre>

    <author>
      <name>Mikhail Bulgakov</name>
      <born>1891-05-15</born>
      <died>1940-03-10</died>
    </author>
    <price>99.99</price>
  </book>


  <book available="true">
    <isbn>999999999</isbn>
    <title>C++ Truths</title>
    <genre>philosophy</genre>

    <author>
      <name>Sumant Tambe</name>
      <born>2012-01-01</born>
    </author>
    <author>
      <name>Archana Potnis</name>
      <born>2012-01-01</born>
    </author>
    <price>9.99</price>
  </book>

  <book>
    <isbn>0679600841</isbn>
    <title>War and Peace</title>
    <genre>history</genre>

    <author>
      <name>Leo Tolstoy</name>
      <born>1828-09-09</born>
      <died>1910-11-20</died>
    </author>
    <price>10</price>
  </book>


  <book available="false">
    <isbn>0679420290</isbn>
    <title>Crime and Punishment</title>
    <genre>philosophy</genre>

    <author>
      <name>Fyodor Dostoevsky</name>
      <born>1821-11-11</born>
      <died>1881-02-09</died>
    </author>
    <author>
      <name>XYZ</name>
      <born>1821-11-11</born>
      <died>1881-02-09</died>
    </author>
    <price>11.99</price>
  </book>

</lib:catalog>
